[Unit]
After=multi-user.target

[Service]
ExecStart=
ExecStartPre=/bin/clear
ExecStart=/usr/bin/python3.12 /mnxmc/main-login.py
StandardInput=tty
StandardOutput=tty
TTYPath=/dev/tty1
TTYReset=yes
TTYVHangup=yes
TTYVTDisallocate=no
User=root
Restart=on-failure
RestartSec=1
